export const LOCAL_LAUNCHER_VERSION = "0.1.17";

export const LOCAL_LAUNCHER_DOWNLOAD_URL = `/desktop/FORBIDDENS_${LOCAL_LAUNCHER_VERSION}_x64-setup.exe`;

export const RECOMMENDED_LAUNCHER_VERSION =
  import.meta.env.VITE_RECOMMENDED_LAUNCHER_VERSION || LOCAL_LAUNCHER_VERSION;

export const LAUNCHER_DOWNLOAD_URL =
  import.meta.env.VITE_LAUNCHER_DOWNLOAD_URL || LOCAL_LAUNCHER_DOWNLOAD_URL;
